backend:
  name: github
  repo: alsharp/alsharp.github.io/ketchenerpost
  branch: gh-pages
  site_domain: hopeful-morse-646b24.netlify.com

media_folder: "images/uploads"

collections:
  - name: "article"
    label: "Article"
    folder: "articles"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: Date }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: Markdown }
      - { name: cover_image, label: Cover Image, widget: Image }
      - { name: author, label: Author }