backend:
  name: github
  repo: alsharp/ketchenerpost
  branch: gh-pages
  site_domain: hopeful-morse-646b24.netlify.com

media_folder: "images/uploads"

collections:
  - name: "article"
    label: "Article"
    folder: "articles/article"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
      - { name: cover_image, label: Cover Image, widget: image }
      - { name: author, label: Author }
      - { name: body, label: Text, widget: markdown }